### ISSUE TITLE
Support for custom rules

### ISSUE THREAD

**Issue by AaronSadlerUK** [elboletaire/password-strength-meter#11]
Is there support to check the password matches our regex rules, such as 1 lowercase, 1 uppercase, a number and symbol?

**Comment by elboletaire** [comment]
Nope, but it's a good idea so I tag is at enhancement for the 2.0.0 version. Thanks!

**Comment by jhoover4** [comment]
Can help out with this if its wanted/needed

**Comment by jackttcoms** [comment]
I see the milestone is at 0%. Do you know any date when u are planning on making some improvements?

Thanks... also i'd take @jhoover4 up on his offer 👍

**Comment by elboletaire** [comment]
Hey @jackttcoms sorry not to answer before, but am pretty busy these days and I don't have enough time to check it. I already explained to jhoover what could be done, but, afaik, he hadn't enough time either.

There's already the PR #6 which should close this issue, but it's not properly tested and it won't work in many cases (that code assumes that objects maintain keys order, and that's not true in js).

Anyway, I really want to improve the package; I even want to create a react component (which would need all the core functions of this module outside, work that I already started but there it is, awaiting for some free time from me), but as said, I don't have too much free time these days.

**Comment by jhoover4** [comment]
Yeah I started a new job, so I got sidetracked, but when things settle down I'll make some PRs.

**Comment by jackttcoms** [comment]
Ah ye, no worries. Same. So many things to do nowadays, these things get sidetracked. I would help but my js knowledge is very limited. I specialse more in PHP, HTML, CSS & ABAP. 

Thanks for your response and no problem. Thanks again.

**Comment by jhoover4** [comment]
Alright here we go team, I'm getting this V2 done lol. @jackttcoms want to help?

Also making this work as a React or Vue component would be awesome. How would we go about that though, any ideas?

**Comment by jackttcoms** [comment]
@jhoover4 oops. when I only just see this email 3 months later :|

I can help if help is still required aha.

**Comment by elboletaire** [comment]
Closed by #35
