### ISSUE TITLE
Support for react native

### ISSUE THREAD

**Issue by isunilapps** [elboletaire/password-strength-meter#12]
Do this have support for react native..? so that i can use it, as custom TextInput Component in react native

**Comment by elboletaire** [comment]
No. AFAIK, jQuery is not react-native compatible, so this plugin ain't be compatible.

I've already an open issue to split this package in multiple ones, and you can see there I want to create it for React. I guess I'll need a different package for react native, as react and native are slightly different, but you can track that issue anyway: #10
