### ISSUE TITLE
manually trigger on password update

### ISSUE THREAD

**Issue by melvinchia** [elboletaire/password-strength-meter#14]
Hi, I programatically update the password field using

~~~js
$("#password_field").val("new_password");
~~~

but the score isn't updated. How do I manually trigger the scoring?

**Comment by melvinchia** [comment]
Found it.. You could probably add a method to do it programatically though..

~~~js
$("#password_field").trigger("keyup").trigger("focus");
~~~

Documenting it in case anybody else needs to do it for now.

Edit: Added focus trigger. If the field was blank and not focused before the .val took effect, the focus trigger brings up the strength meter. Without the focus, the score is updated but the visuals aren't.

**Comment by elboletaire** [comment]
I don't see the need to add a method for something that you can do as you stated (using trigger).

BTW, I've updated your comments to properly use codeblocks :wink:
