### ISSUE TITLE
typo: "charecters"

### ISSUE THREAD

**Issue by melvinchia** [elboletaire/password-strength-meter#15]
Found a typo in your default goodPass:

`goodPass:"Medium; try using special charecters"`

Should read:

`goodPass:"Medium; try using special characters"`

**Comment by elboletaire** [comment]
Thanks for the note! Anyway this part is being refactored so I'll close this in favor of #11

**Comment by katapofatico** [comment]
Hello @elboletaire,
The miss-typo in default texts remains on 1.1.0.
Good day :)

**Comment by elboletaire** [comment]
It's fixed in version 2, not version 1. Anyway, I searched for it and I cannot find the typo, can you please link directly to it?

**Comment by katapofatico** [comment]
Ok, sorry: I downloaded from "Releases" tab, where the last version is 1.1.0. I checked the "Tags" tab and downloaded the last version there.
Thanks!

**Comment by elboletaire** [comment]
I forgot about that "release"... just in case you don't know: github releases are something custom, most projects only use tags to define the new versions, and all tags also appear in the releases section, but tags usually appear folded, you need to unfold them :)

Anyway, I have updated the latest release to point to the latest tag... but it's a PITA remembering to update this xD
