### ISSUE TITLE
Material design

### ISSUE THREAD

**Issue by eliseuborges** [elboletaire/password-strength-meter#19]
Hi, 

I'm working with bootstrap material design and would like to show colorbar below the password field. How to do? 

![image](https://user-images.githubusercontent.com/15690538/45838997-791ac700-bce9-11e8-80ad-7fd31ee21404.png)

**Comment by elboletaire** [comment]
Sorry but this is nothing related to password-strength-meter itself, but to material design. If you have questions or don't know how to do something (in general) you better ask in stackoverflow. Github is not for questions and answers, but for bugs/issues & pull requests.

Thanks
