### ISSUE TITLE
we can't use this plugin within webpack based project

### ISSUE THREAD

**Issue by thamerbelfkihthamer** [elboletaire/password-strength-meter#24]
I'm working on a Laravel project, and I'm using Webpack. when I add this plugin within my js file with require and then when I generate one file app.js to merge all my js files, I have found that this plugin generates a new jquery as a dependency for itself, so that creates conflict with my default jquery. the result of all that is 2 jquery bib within app.js file that generated after the merge of all my *.js files.

So here, we should make jquery within this plugin as peerDependency.

Anyone can fix this, please? I'm not javascript guy to resolve this issue.

**Comment by elboletaire** [comment]
My fault. jquery should not be as a `dependency` but as a `peerDependency`.

**Comment by thamerbelfkihthamer** [comment]
@elboletaire how we can resolve this please ?

**Comment by elboletaire** [comment]
Fixed in 1.2.2

**Comment by elboletaire** [comment]
@thamerbelfkihthamer try with the just published 1.2.2 version and tell me if it really fixed the issue. If it wasn't that, then may be something related to how are you compiling your scripts with webpack (don't forget that this is a jquery plugin and [it does not behave like other npm packages when it comes to importing it](https://blog.npmjs.org/post/112064849860/using-jquery-plugins-with-npm)).

**Comment by thamerbelfkihthamer** [comment]
@elboletaire  yes, this resolves it. and it works fine now. Thanks
