### ISSUE TITLE
Bootstrap input-group

### ISSUE THREAD

**Issue by hmichal-dev** [elboletaire/password-strength-meter#3]
Progress bar is not visible when Bootstrap input group is used.

	<div class="form-group">
		<div class="input-group">
			<span class="input-group-addon">
				<span class="glyphicon glyphicon-lock" aria-hidden="true"></span>
			</span>
			<input id="password" class="password-progress-bar form-control" type="password">
			
			<div class="pass-wrapper" style="display: none;"><div class="pass-graybar"><div class="pass-colorbar"></div></div></div>
		</div>
	</div>

**Comment by elboletaire** [comment]
@michal-hary I may need to add a closestSelector setting or something similar for this case, because in this case you need the extra layers to be added outside the .input-group.

I'm out now (answering from Telegram); when I can I'll take a look into it.

Thanks for the report!

**Comment by hmichal-dev** [comment]
@elboletaire  Thanks for fast response. 

It would be great to add selectors in options. Better configuration would make this library much more flexible. Another useful feature is configuration to put text in color bar.

**Comment by jhoover4** [comment]
Opened PR for this: #31

**Comment by elboletaire** [comment]
Done in 246c11c8137edc4f8908caca3b98a21b32de1d31. You can check a working example [in the demo page](https://elboletaire.github.io/password-strength-meter/).
