### ISSUE TITLE
NPM Build is Old

### ISSUE THREAD

**Issue by jmortlock** [elboletaire/password-strength-meter#33]
Hi

Looks like the npm published code (password.min.js) is not up to date, for example goodPass still has the typo: 
```
goodPass:"Medium; try using special charecters"
```

**Comment by elboletaire** [comment]
@jmortlock I’m out on vacation 🙃

I’ll publish the version as soon as I’m at home again + have enough time to finish the remaining issues (take a look to the issues/pr, you’ll see I asked things that weren’t answered, reason why I didn’t make the version in that moment)

**Comment by elboletaire** [comment]
Updated to 2.0.0
