### ISSUE TITLE
Typo in the available options example

### ISSUE THREAD

**Issue by Jorden-** [elboletaire/password-strength-meter#34]
In your example about the possible options for the password meter the following option has a typo:
`goodPass: 'Medium; try using special charecters',`

`charecters` should be: `characters`

**Comment by elboletaire** [comment]
This has been stated multiple times. It's fixed but not published. 

As soon as version 1.3.0 is published you'll see it changed :)

Thanks for the issue, though :smiley:

**Comment by elboletaire** [comment]
Version 2.0.0, sorry. I forgot there were breaking changes in the new version.
