### ISSUE TITLE
messages in steps are not replaced

### ISSUE THREAD

**Issue by leandroruel** [elboletaire/password-strength-meter#42]
tried put my own messages but he keeps putting the english messages over it, but just for steps:

```js
$("#password").password({
        enterPass: 'Digite sua senha',
        shortPass: 'A senha é muito curta',
        containsField: 'A senha contém seu nome de usuário',
        steps: {
            // Easily change the steps' expected score here
            13: 'Senha muito insegura',
            23: 'Fraco; tente combinar letras e números',
            67: 'Médio; tente usar caracteres especiais',
            94: 'Senha forte!',
        },
    });
```

**Comment by elboletaire** [comment]
Are you using the minified version?

**Comment by leandroruel** [comment]
i'm using it with Laravel Mix, who uses webpack under the hood, so... i think he minifies it all

**Comment by elboletaire** [comment]
@leandroruel IDK how does Laravel Mix, but it may be taking the defined `main` key in `package.json`, which points to the already minified version. If that's the case, this is already being tracked in #40

**Comment by jhoover4** [comment]
Nice!

**Comment by elboletaire** [comment]
@leandroruel can you please confirm this issue is fixed? Don't forget to update your package, ofc :).

**Comment by fabriceci** [comment]
The issue is fixed, I had the same problem in the latest release, but it's ok in the master.
