### ISSUE TITLE
Disabling text warnings and still listening for password.text event

### ISSUE THREAD

**Issue by ghost** [elboletaire/password-strength-meter#8]
password.text event is not fired if text is disabled via options. 

I don't want the plugin to render the text message. Instead I need to get the status text and render it my self. How can i achieve this?

**Comment by elboletaire** [comment]
You could use `password.score` instead, and make your own array of messages, something like:

~~~js
const scores = {
  0: 'First message',
  10: 'Second message',
  200: 'Third message',
}
$('#password').on('password.score', (e, score) => {
  Object.keys(scores).forEach((sc) => {
    if (score <= sc) {
      $('.your-message-holder').text(scores[sc]);
    }
  })
})
~~~

Should do the trick.

Sorry for the delay btw, if you consider this is what you were searching for I'll close the ticket (or close it by yourself 😉).

**Comment by elboletaire** [comment]
Does this fit your needs @ilterocal?

**Comment by elboletaire** [comment]
Closed due to inactivity.
